# Generated by Django 3.1 on 2020-09-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('delivery_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_datetime', models.DateTimeField()),
                ('delivery_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.productsets')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.recipient')),
            ],
        ),
    ]
