# Generated by Django 3.1 on 2020-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsets',
            options={'verbose_name_plural': 'product sets'},
        ),
        migrations.AddField(
            model_name='productsets',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsets',
            name='weight',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
