# Generated by Django 3.1 on 2020-09-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200911_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsets',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
